---
name: spellchecktest
on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.**'
    branches:
      - main
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    steps:
      - uses: actions/checkout@v4
      - uses: tbroadley/spellchecker-cli-action@v1
        with:
          files: "./cook/**/*.cook ./docs/**/*.md"
          quiet: false
          dictionaries: "./dictionary.txt"
