---
name: spellcheck
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run spellcheck
        uses: tbroadley/spellchecker-cli-action@v1
        with:
          quiet: true
          dictionaries: "./dictionary.txt"
          config: "./.spellcheckerrc.yml"
