name: Conditional Variable Example

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      MOD_ONLY: ${{ steps.step3.outputs.MOD_ONLY }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=${{ github.event_name }}" >> "$GITHUB_OUTPUT"
      - id: step3
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "MOD_ONLY=yes" >> "$GITHUB_OUTPUT"
          else; then
            echo "MOD_ONLY=no" >> "$GITHUB_OUTPUT"
          fi
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
          MOD_ONLY: ${{ steps.step3.outputs.MOD_ONLY }}
        run: echo "$OUTPUT1 $OUTPUT2 $MOD_ONLY"
        
