name: Conditional Variable Example

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  set-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable based on event
        run: |
          echo "${{ github.event_name }}" 
          echo "EVENT_TYPE=test" >> $GITHUB_ENV
          # if [ "${{ github.event_name }}" == "push" ]; then
          #   echo "EVENT_TYPE=push" >> $GITHUB_ENV
          # else; then
          #fi
      - name: Print event type
        run: echo "The event type is $EVENT_TYPE"

  use-variable:
    runs-on: ubuntu-latest
    needs: set-variable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print event type
        run: echo "The event type is $EVENT_TYPE"
